### ISSUE TITLE
"3rd Charter" tasks - track list

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/omikhleia-sile-packages#13]
So to recap our progress so far:
- First "3-month charter" (Sept-Nov 2021) was targeted on building packages and classes for my needs = completed
- "Second charter" (Jan-March 2022 > extended to June 2022) was targeted on typesetting an actual book (a.k.a. Almaq project) = completed (sort of, awaiting confirmation by mid-June, but the greenlight is expected).

Will we go for a "3rd charter" (approx. July-Oct. 2022) after that ? The decision is still pending.

Yet we may tentatively track its expected scope:
- [x] Review and improve "styles" package (Priority 1 = complete at least what we have started).
- [x] Indexer stuff - see SILE https://github.com/sile-typesetter/sile/issues/1339 (Priority 2 - If it's not done, next project is heavily compromised)
- [x] More styles in "omipoetry" (Priority 3, though likely easy, no need for it yet)
- [x] Markdown with Pandoc Lua (a neat PoC was done, so Priority 3 to get at least a minimal working version) = see #23 
- [ ] Segond Bible from USFX source (a PoC was done... Priority 4, just for the sake of initiating something, incl. sidenotes...) = see #22 
- [x] Typesetter mess (see SILE https://github.com/sile-typesetter/sile/issues/1361) = hornets nest... it's a deadly blocker too if our current hacks fail in more general cases... Priority not assessed as it would mean migrating to SILE 0.13 (see below)

Likely out of scope at this date:
- Migrating from SILE 0.12.5 to 0.13.x when available. Lots of API changes but no clear benefits (yet) for our projects?
- Typesetter mess again: consider how/when to remove our various ugly "hacks" (in the `hacks/` folder)...

**Comment by Omikhleia** [comment]
> More styles in "omipoetry"

Addressed in resilient https://github.com/Omikhleia/resilient.sile/pull/6
(Still lagging behind of the items in this old list)

**Comment by Omikhleia** [comment]
>  Typesetter mess (see SILE https://github.com/sile-typesetter/sile/issues/1361) = hornets nest... it's a deadly blocker too if our current hacks fail in more general cases...

Addressed
- In resilient: https://github.com/Omikhleia/resilient.sile/commit/c6b350b1ff96b426605555f5a47a4338498b6297
- In SILE core: https://github.com/sile-typesetter/sile/pull/1717

**Comment by Omikhleia** [comment]
> Review and improve "styles" package (Priority 1 = complete at least what we have started).

Moved to https://github.com/Omikhleia/resilient.sile/issues/12

**Comment by Omikhleia** [comment]
> Indexer stuff (...)

Move to https://github.com/Omikhleia/resilient.sile/issues/17

**Comment by Omikhleia** [comment]
The last item not covered in this list was "Segond Bible from USFX source" -- Which considered USFX support (XML schema for Scriptures). In [resilient.sile](https://github.com/Omikhleia/resilient.sile) we moved towards rather supporting USX (another XML schema for Scriptures) -- so the USFX WIP is now obsolete.
